name: localstack
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4571:4571' # Secrets Manager
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
      - DEFAULT_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:1212
      - DISABLE_CORS_CHECKS=1
    volumes:
      - './localstack:/var/lib/localstack'
      - './localstack/init:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'
